class exit: raise Exception('Successful')
